[metadata]
name = "commonfate_provider"
version = "0.1.5"
description = "This is the core Provider framework on top of which Access Provider are written."
authors = ["Chris Norman <chris@commonfate.io>", "Manish Chaulagain <manish@commonfate.io>", "Josh Wilkes <josh@commonfate.io>", "Jack Meyer <jack@commonfate.io>", "Jordi Hermoso <jordi@commonfate.io>"]
readme = "README.md"
include = ["commonfate_provider/**/*.py"]
## TODO: Not excluding test from the build
exclude = ["commonfate_provider/tests/**"]

[options]
python = "^3.9"
toml = "0.10.2"
click = "8.1.3"
pytest = "7.2.0"
typing-extensions = "4.4.0"
pydantic = "1.10.2"
treelib = "1.6.1"
