name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get tag version
        id: tag
        run: |
          TAG=${{github.ref_name}}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Update package version
        run: |
          echo "updating package version to ${{steps.tag.outputs.VERSION}}"
          poetry version ${{ steps.tag.outputs.VERSION }}

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
