name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.3.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get tag version
        id: tag
        run: |
          TAG=${{github.ref_name}}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Update package version
        run: |
          echo "updating package version to ${{steps.tag.outputs.VERSION}}"
          poetry version ${{ steps.tag.outputs.VERSION }}

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
